// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq468mmN_c57ljaCkG1ETURXR8ovb414U',
    appId: '1:27589609534:web:9724d017e805f103f4a96f',
    messagingSenderId: '27589609534',
    projectId: 'todoapp-1e4c5',
    authDomain: 'todoapp-1e4c5.firebaseapp.com',
    storageBucket: 'todoapp-1e4c5.appspot.com',
    measurementId: 'G-1JC6H1921S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh5T7jw6J9TgyZkoW00kZldu7rWQA9ujI',
    appId: '1:27589609534:android:52c8bc5d604370b2f4a96f',
    messagingSenderId: '27589609534',
    projectId: 'todoapp-1e4c5',
    storageBucket: 'todoapp-1e4c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Kk1dlrObEHjpP9LCkoFah9YddiaNJrs',
    appId: '1:27589609534:ios:1b5d65ebd4f7a76bf4a96f',
    messagingSenderId: '27589609534',
    projectId: 'todoapp-1e4c5',
    storageBucket: 'todoapp-1e4c5.appspot.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Kk1dlrObEHjpP9LCkoFah9YddiaNJrs',
    appId: '1:27589609534:ios:731e8e88a76bea53f4a96f',
    messagingSenderId: '27589609534',
    projectId: 'todoapp-1e4c5',
    storageBucket: 'todoapp-1e4c5.appspot.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
